version: 2
updates:
  # Python backend (pip)
  - package-ecosystem: "pip"
    directory: "/python-backend" # path to requirements.txt
    schedule:
      interval: "daily"

  # NPM backend
  - package-ecosystem: "npm"
    directory: "/backend-disinformation-game" # path to package.json
    schedule:
      interval: "daily"

  # NPM frontend
  - package-ecosystem: "npm"
    directory: "/frontend-disinformation-game" # path to package.json
    schedule:
      interval: "daily"
